# Generated by Django 6.0.7 on 2026-07-30 10:23

import django.db.models.deletion
import hame.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hame', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='osm_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='osm_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='locationcategory',
            name='osm_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='locationcategory',
            name='osm_value',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.ForeignKey(default=hame.models.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='hame.locationcategory'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'osm')), fields=('osm_type', 'osm_id'), name='unique_osm_type_id'),
        ),
        migrations.AddConstraint(
            model_name='locationcategory',
            constraint=models.UniqueConstraint(fields=('osm_key', 'osm_value'), name='unique_osm_key_value'),
        ),
    ]
