# Generated by Django 6.0.7 on 2026-08-03 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hame', '0002_location_osm_id_location_osm_type_location_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCategoryKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_key', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_osm_type_id',
        ),
        migrations.RemoveConstraint(
            model_name='locationcategory',
            name='unique_osm_key_value',
        ),
        migrations.AddField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(to='hame.locationcategory'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('osm_type', 'osm_id'), name='unique_osm_type_id'),
        ),
        migrations.AddField(
            model_name='locationcategory',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hame.locationcategorykey'),
        ),
        migrations.AddConstraint(
            model_name='locationcategory',
            constraint=models.UniqueConstraint(fields=('key', 'osm_value'), name='unique_osm_key_value'),
        ),
        migrations.RemoveField(
            model_name='location',
            name='category',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='location',
            name='source',
        ),
        migrations.RemoveField(
            model_name='locationcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='locationcategory',
            name='osm_key',
        ),
    ]
