# Generated by Django 6.0.7 on 2026-08-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hame', '0003_locationcategorykey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='accessible_toilet',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown'), ('NA', 'Not Applicable')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='userentry',
            name='auto_doors',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown'), ('NA', 'Not Applicable')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='userentry',
            name='braille_signage',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown'), ('NA', 'Not Applicable')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='userentry',
            name='disabled_bay',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown'), ('NA', 'Not Applicable')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='userentry',
            name='gradient',
            field=models.CharField(choices=[('F', 'Flat'), ('G', 'Gentle'), ('M', 'Moderate'), ('S', 'Steep'), ('U', 'Unknown'), ('NA', 'Not applicable')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='userentry',
            name='hearing_loop',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown'), ('NA', 'Not Applicable')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='userentry',
            name='level_floor_or_lift',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown'), ('NA', 'Not Applicable')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='userentry',
            name='nonvisual_crossing_cues',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown'), ('NA', 'Not Applicable')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='userentry',
            name='parking',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown'), ('NA', 'Not Applicable')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='userentry',
            name='quiet_space',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown'), ('NA', 'Not Applicable')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='userentry',
            name='surface_type',
            field=models.CharField(choices=[('P', 'Paved/smooth'), ('C', 'Cobblestone'), ('G', 'Gravel'), ('S', 'Sand'), ('B', 'Bumpy/uneven'), ('U', 'Unknown'), ('NA', 'Not applicable')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='userentry',
            name='tactile_paving',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown'), ('NA', 'Not Applicable')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='userentry',
            name='wheelchair',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown'), ('NA', 'Not Applicable')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='text_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
