# Generated by Django 6.0.7 on 2026-08-24 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hame', '0004_userentry_accessible_toilet_userentry_auto_doors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userentry',
            constraint=models.UniqueConstraint(fields=('location', 'user'), name='unique_entry_per_user_location'),
        ),
    ]
